In [ ]:
import os
import json
import gzip
import pandas as pd
from urllib.request import urlopen
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.svm import LinearSVC 
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report

In [ ]:
%cd '/content/drive/MyDrive/Project_DevC'
!ls

/content/drive/MyDrive/Project_DevC
clone_cmt_tiki	     Data_ChungKhoan14518.txt	       Untitled10.ipynb
clone_data	     datadepvail.csv
Data_Bank100518.txt  scrapingweb_bookingcomment.ipynb


In [ ]:
txt = open('Data_Bank100518.txt').read()
print(txt)

<obj>Rất lấy làm tiếc khi hôm nay không có chi nhánh nào thực hiện giao dịch, bạn phải chờ vài hôm nữa
<neg>Rất tiếc khi phải thông báo giao dịch của bạn không thành công
<neg>Thẻ của bạn đã bị khóa rồi thì làm sao mà rút được tiền
<neg>Rất tiếc là thẻ của bạn đã bị khóa, chúng tôi không thể thực hiện giao dịch giúp bạn được
<obj>để làm vừa lòng khách hàng, Chúng tôi tận tâm phục vụ quý khách
<obj>Chúng tôi luôn luôn tận tâm phục vụ khách hàng chu đáo nhất.
<obj>T2 hẹn lên ngân hàng phục vụ tận tâm luôn
<obj>T2 hẹn bạn lên ngân hàng, chúng tôi phục vụ tận tâm luôn.
<neg>Thẻ ATM bên NH này phí đắt
<obj>Tôi dùng thẻ thưởng thôi, ATM ý
<neg>BIDV dịch vụ thì chậm chạp, mất thì giờ, lại còn rườm rà thủ tục kiểm tra. Trong khi bọn Vietcombank chưa đầy 1 phút!
<neg>Dịch vụ của Vcb phục chán quá, nhân viên thì chậm chạp, chán thật. Trong khi ngân hàng đối thủ thì phục vụ rất nhanh!
<neg>Dịch vụ phục chán quá, nhân viên thì chậm chạp, chán thật!
<neg>sinh viên học xong không xin được việc làm v

In [ ]:
data = pd.read_csv("datadepvai.csv")
data

Unnamed: 0                                            comment  labels
0              0  Mình gọi một suất bánh tráng trộn ,bánh tráng ...     0.0
1              1  Áo dày, đường may chắc chắn. Màu xanh đen rất ...     1.0
2              2  Áo mưa xịn, k thấm nước, đường may chắc chắn, ...     2.0
3              3  Sản phẩm rộng rãi, dài, ngồi chùm kín chân, mì...     0.0
4              4  Áo mưa nhìn đẹp lắm. Mặc thử rất vừa. Tay hơi ...     2.0
...          ...                                                ...     ...
9131        9131  Hàng OK lãm đẹp ,sạch mang vào êm mà đế giầy r...     2.0
9132        9132  Giày đế dẻo, vải nên form không đứng, ok mang ...     2.0
9133        9133       chất lượng ok với giá tiền này thì  rất tốt.     2.0
9134        9134  - Màu cam đẹp các bác à. Các đường nét năm nay...     2.0
9135        9135                                         cũng ok đó     2.0

[9136 rows x 3 columns]

In [ ]:
data = data.drop(['Unnamed: 0'],axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9136 entries, 0 to 9135
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   comment  9132 non-null   object 
 1   labels   9128 non-null   float64
dtypes: float64(1), object(1)
memory usage: 142.9+ KB


In [ ]:
data = data.dropna() 

In [ ]:
data['labels'].value_counts()

0.0    3925
2.0    3125
1.0    2074
Name: labels, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(data['comment'],data['labels'],test_size = 0.2 ,random_state = 42)

In [ ]:
tfidf_vectorizer=TfidfVectorizer(max_df=0.95)

tfidf_train=tfidf_vectorizer.fit_transform(x_train) 
tfidf_test=tfidf_vectorizer.transform(x_test)

In [ ]:
num_folds = 10
scoring = 'accuracy'
seed = 42

In [ ]:
models = [] 
models.append(('LR', LogisticRegression()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('MNB',MultinomialNB()))
models.append(('CNB',ComplementNB()))
models.append(('BNB',BernoulliNB()))
models.append(('PAC', PassiveAggressiveClassifier(max_iter=50)))
models.append(('LinearSVC',LinearSVC()))

In [ ]:
results = []
names = []
for name, model in models:
  kfold = KFold(n_splits=num_folds,random_state=seed,shuffle=True)
  cv_results = cross_val_score(model, tfidf_train, y_train, cv=kfold, scoring=scoring)
  results.append(cv_results)
  names.append(name)
  msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
  print(msg)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LR: 0.831957 (0.010754)
KNN: 0.420185 (0.017257)
CART: 0.808678 (0.012626)
MNB: 0.774142 (0.011997)
CNB: 0.771588 (0.010772)
BNB: 0.771138 (0.010858)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


PAC: 0.825950 (0.010716)
LinearSVC: 0.837664 (0.010199)


In [ ]:
results =  []
kernels = ['linear', 'rbf', 'poly']
for kernel in kernels:
  model = SVC(kernel=kernel)
  kfold = KFold(n_splits=num_folds,random_state=seed,shuffle=True)
  cv_results = cross_val_score(model, tfidf_train, y_train, cv=kfold, scoring=scoring)
  results.append(cv_results)
  msg = "%s: %f (%f)" % (kernel, cv_results.mean(), cv_results.std())
  print(msg)

linear: 0.834511 (0.011013)
rbf: 0.868600 (0.010608)
poly: 0.832408 (0.014752)


In [ ]:
cs = [0.1, 1, 10, 100, 1000]
for c in cs : 
  model = SVC(kernel='linear', C=c)
  kfold = KFold(n_splits=num_folds,random_state=seed,shuffle=True)
  cv_results = cross_val_score(model, tfidf_train, y_train, cv=kfold, scoring=scoring)
  msg = "%f: %f (%f)" % (c, cv_results.mean(), cv_results.std())
  print(msg)

0.100000: 0.790061 (0.013019)
1.000000: 0.834511 (0.011013)
10.000000: 0.834661 (0.009670)
100.000000: 0.818144 (0.016366)
1000.000000: 0.807029 (0.011716)


In [ ]:
for alpha in np.arange(0,1,.1):
    nb_classifier = MultinomialNB(alpha=alpha)
    kfold = KFold(n_splits=num_folds, random_state=seed,shuffle=True)
    cv_results = cross_val_score(nb_classifier,tfidf_train, y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    msg= "%f: %f (%f)" % (alpha, cv_results.mean(), cv_results.std())
    print(msg)

0.000000: 0.767835 (0.012511)
0.100000: 0.787507 (0.010102)
0.200000: 0.789008 (0.007403)


/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
/usr/local/lib/python3.6/dist-packages/sklearn/nai

0.300000: 0.789610 (0.010140)
0.400000: 0.787357 (0.010779)
0.500000: 0.785255 (0.012847)
0.600000: 0.780450 (0.013503)
0.700000: 0.780300 (0.012142)
0.800000: 0.777596 (0.011062)
0.900000: 0.776244 (0.010102)


In [ ]:
ensembles = []
ensembles.append(('AB', AdaBoostClassifier()))
ensembles.append(('GBM', GradientBoostingClassifier()))
ensembles.append(('RF', RandomForestClassifier()))
ensembles.append(('ET', ExtraTreesClassifier()))
results = []
names = []
for name, model in ensembles:
  kfold = KFold(n_splits=num_folds, random_state=seed,shuffle=True)
  cv_results = cross_val_score(model, tfidf_train, y_train, cv=kfold, scoring=scoring)
  msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
  print(msg)

AB: 0.759424 (0.010262)
GBM: 0.796218 (0.018358)
RF: 0.864547 (0.012657)
ET: 0.864547 (0.011680)


In [ ]:
lr =LogisticRegression()
lr.fit(tfidf_train,y_train) 
def most_informative_feature_for_binary_classification(vectorizer, classifier, n):
    class_labels = classifier.classes_
    feature_names = vectorizer.get_feature_names()
    topn_class1 = sorted(zip(classifier.coef_[0], feature_names))[:n]
    topn_class2 = sorted(zip(classifier.coef_[0], feature_names))[-n:]
    for coef, feat in topn_class1:
        print(class_labels[2], coef, feat)
    print()
    for coef, feat in reversed(topn_class2):
        print(class_labels[0], coef, feat)
    
most_informative_feature_for_binary_classification(tfidf_vectorizer, lr, n=10)

2.0 -5.907217704311905 đẹp
2.0 -4.976409300253322 ok
2.0 -4.388232741411855 nhanh
2.0 -3.199087824113854 tốt
2.0 -2.863343081278368 nhưng
2.0 -2.658028772746246 ổn
2.0 -2.5572876296668454 hợp
2.0 -2.408295232491859 mát
2.0 -2.2461415577963506 êm
2.0 -2.1908041330411887 tạm

0.0 4.787536556579127 không
0.0 3.3051168823498585 ko
0.0 3.208186770022575 tệ
0.0 2.499465153942024 xấu
0.0 2.482987398638271 kém
0.0 2.4604997885382107 thất
0.0 2.307541001728948 vọng
0.0 1.982227935352556 mỏng
0.0 1.7955762420344281 lỗi
0.0 1.7891388229941705 chán


In [ ]:
lr =LogisticRegression()
lr.fit(tfidf_train,y_train) 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
import pickle 

In [ ]:
Pkl_Filename = "LR_Model.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    Pickled_LR_Model = pickle.load(file)

Pickled_LR_Model

In [ ]:
y_pred = lr.predict(tfidf_test)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8258258258258259
[[557  41  15]
 [ 87 268  65]
 [ 31  51 550]]
              precision    recall  f1-score   support

         0.0       0.83      0.91      0.86       613
         1.0       0.74      0.64      0.69       420
         2.0       0.87      0.87      0.87       632

    accuracy                           0.83      1665
   macro avg       0.81      0.81      0.81      1665
weighted avg       0.82      0.83      0.82      1665



In [ ]:
check = np.array(y_pred -y_test)
check = list(check)

In [ ]:
comment = data.comment.values
comment_test = y_test.to_numpy()

In [ ]:
for index, check_cmt in enumerate(check):
  if check_cmt != 0:
    print(comment[index])
    print("y_pred : " + str(y_pred[index]))
    print("y_test : " + str(comment_test[index]))

Áo Sơ Mi Nam KOJIBA Dài Tay Công Sở chất liệu tốt, vải đẹp, mặc lên dáng chuẩn.
Màu sắc rất ưng ý, giá thành rẻ so với thị trường
Sẽ tiếp tục ủng hộ Áo Sơ Mi Nam KOJIBA Dài Tay Công Sở
y_pred : 2.0
y_test : 1.0
Tốt lắm mn
y_pred : 1.0
y_test : 0.0
gói hàng cẩn thận ok
y_pred : 2.0
y_test : 1.0
vải dày nha mng hình in rất rõ và đẹp , các bạn nên mua đi ạ như hình luôn á , cảm nhận thật lòng của mình nhé ❤😄 vải dày nha mng hình in rất rõ và đẹp , các bạn nên mua đi ạ như hình luôn á , cảm nhận thật lòng của mình nhé ❤😄
y_pred : 1.0
y_test : 0.0
thực sự thì vs giá tiền nv rất rất  .😍😍
duy nhất 1 chút lỗi là đường chỉ ở cổ áo hơi lỗi xíu nhưng vẫn ok 
y_pred : 0.0
y_test : 1.0
Sản phẩm rất ưng ý, chất liệu mềm mại, mát mẻ, vừa rẻ, vừa đẹp, đóng gói rất kỹ, giao nhanh  
y_pred : 2.0
y_test : 1.0
Sp đẹp & gọn! Có thể dùng tuốc nơ vít để vặn vít vào! Do ko có hướng dẫn, nên mn xem hình, ráp sơ trước để đảm bảo các thanh đúng vị trí, rồi hãy vặn vít chặt vào. Đẹp & gọn!


In [ ]:
pip install pyvi

     |████████████████████████████████| 8.5MB 7.6MB/s 
     |████████████████████████████████| 747kB 35.0MB/s 


In [ ]:
from pyvi import ViTokenizer, ViPosTagger

print(ViTokenizer.tokenize("Trường đại học bách khoa hà nội"))

print(ViPosTagger.postagging(ViTokenizer.tokenize("Trường đại học Bách Khoa Hà Nội")))

from pyvi import ViUtils
print(ViUtils.remove_accents("Trường đại học bách khoa hà nội"))

from pyvi import ViUtils
print(ViUtils.add_accents('truong dai hoc bach khoa ha noi'))

Trường đại_học bách_khoa hà_nội
(['Trường', 'đại_học', 'Bách_Khoa', 'Hà_Nội'], ['N', 'N', 'Np', 'Np'])
b'Truong dai hoc bach khoa ha noi'
Trường Đại học Bách Khoa hà nội


In [ ]:
a = ViPosTagger.postagging(ViTokenizer.tokenize("sản phẩm này không đẹp"))
a

(['sản_phẩm', 'này', 'không', 'đẹp'], ['N', 'P', 'R', 'A'])